/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zoxal_labs_iapd_usb_nativefacade_NativeFacade */

#ifndef _Included_com_zoxal_labs_iapd_usb_nativefacade_NativeFacade
#define _Included_com_zoxal_labs_iapd_usb_nativefacade_NativeFacade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zoxal_labs_iapd_usb_nativefacade_NativeFacade
 * Method:    getDevPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zoxal_labs_iapd_usb_nativefacade_NativeFacade_getDevPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zoxal_labs_iapd_usb_nativefacade_NativeFacade
 * Method:    getLabel
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zoxal_labs_iapd_usb_nativefacade_NativeFacade_getLabel
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
